// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageBody.proto

package com.striveonger.study.task.context;

public final class MessageBodyOuterClass {
  private MessageBodyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.striveonger.study.task.context.MessageBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
     */
    boolean containsData(
        java.lang.String key);
    /**
     * Use {@link #getDataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData>
    getData();
    /**
     * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
     */
    java.util.Map<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData>
    getDataMap();
    /**
     * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
     */
    /* nullable */
com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData getDataOrDefault(
        java.lang.String key,
        /* nullable */
com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData defaultValue);
    /**
     * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
     */
    com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData getDataOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.striveonger.study.task.context.MessageBody}
   */
  public static final class MessageBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.striveonger.study.task.context.MessageBody)
      MessageBodyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageBody.newBuilder() to construct.
    private MessageBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageBody() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageBody();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.striveonger.study.task.context.MessageBodyOuterClass.internal_static_com_striveonger_study_task_context_MessageBody_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.striveonger.study.task.context.MessageBodyOuterClass.internal_static_com_striveonger_study_task_context_MessageBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.class, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.Builder.class);
    }

    public interface ColumnDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.striveonger.study.task.context.MessageBody.ColumnData)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * 可重复的 repeated
       * </pre>
       *
       * <code>repeated string entry = 1;</code>
       * @return A list containing the entry.
       */
      java.util.List<java.lang.String>
          getEntryList();
      /**
       * <pre>
       * 可重复的 repeated
       * </pre>
       *
       * <code>repeated string entry = 1;</code>
       * @return The count of entry.
       */
      int getEntryCount();
      /**
       * <pre>
       * 可重复的 repeated
       * </pre>
       *
       * <code>repeated string entry = 1;</code>
       * @param index The index of the element to return.
       * @return The entry at the given index.
       */
      java.lang.String getEntry(int index);
      /**
       * <pre>
       * 可重复的 repeated
       * </pre>
       *
       * <code>repeated string entry = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the entry at the given index.
       */
      com.google.protobuf.ByteString
          getEntryBytes(int index);
    }
    /**
     * <pre>
     **
     * 列数据
     * </pre>
     *
     * Protobuf type {@code com.striveonger.study.task.context.MessageBody.ColumnData}
     */
    public static final class ColumnData extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.striveonger.study.task.context.MessageBody.ColumnData)
        ColumnDataOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ColumnData.newBuilder() to construct.
      private ColumnData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ColumnData() {
        entry_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new ColumnData();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.striveonger.study.task.context.MessageBodyOuterClass.internal_static_com_striveonger_study_task_context_MessageBody_ColumnData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.striveonger.study.task.context.MessageBodyOuterClass.internal_static_com_striveonger_study_task_context_MessageBody_ColumnData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData.class, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData.Builder.class);
      }

      public static final int ENTRY_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private com.google.protobuf.LazyStringList entry_;
      /**
       * <pre>
       * 可重复的 repeated
       * </pre>
       *
       * <code>repeated string entry = 1;</code>
       * @return A list containing the entry.
       */
      public com.google.protobuf.ProtocolStringList
          getEntryList() {
        return entry_;
      }
      /**
       * <pre>
       * 可重复的 repeated
       * </pre>
       *
       * <code>repeated string entry = 1;</code>
       * @return The count of entry.
       */
      public int getEntryCount() {
        return entry_.size();
      }
      /**
       * <pre>
       * 可重复的 repeated
       * </pre>
       *
       * <code>repeated string entry = 1;</code>
       * @param index The index of the element to return.
       * @return The entry at the given index.
       */
      public java.lang.String getEntry(int index) {
        return entry_.get(index);
      }
      /**
       * <pre>
       * 可重复的 repeated
       * </pre>
       *
       * <code>repeated string entry = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the entry at the given index.
       */
      public com.google.protobuf.ByteString
          getEntryBytes(int index) {
        return entry_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < entry_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, entry_.getRaw(i));
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < entry_.size(); i++) {
            dataSize += computeStringSizeNoTag(entry_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getEntryList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData)) {
          return super.equals(obj);
        }
        com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData other = (com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData) obj;

        if (!getEntryList()
            .equals(other.getEntryList())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getEntryCount() > 0) {
          hash = (37 * hash) + ENTRY_FIELD_NUMBER;
          hash = (53 * hash) + getEntryList().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       **
       * 列数据
       * </pre>
       *
       * Protobuf type {@code com.striveonger.study.task.context.MessageBody.ColumnData}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.striveonger.study.task.context.MessageBody.ColumnData)
          com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.striveonger.study.task.context.MessageBodyOuterClass.internal_static_com_striveonger_study_task_context_MessageBody_ColumnData_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.striveonger.study.task.context.MessageBodyOuterClass.internal_static_com_striveonger_study_task_context_MessageBody_ColumnData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData.class, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData.Builder.class);
        }

        // Construct using com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          entry_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.striveonger.study.task.context.MessageBodyOuterClass.internal_static_com_striveonger_study_task_context_MessageBody_ColumnData_descriptor;
        }

        @java.lang.Override
        public com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData getDefaultInstanceForType() {
          return com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData.getDefaultInstance();
        }

        @java.lang.Override
        public com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData build() {
          com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData buildPartial() {
          com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData result = new com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData(this);
          buildPartialRepeatedFields(result);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartialRepeatedFields(com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData result) {
          if (((bitField0_ & 0x00000001) != 0)) {
            entry_ = entry_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entry_ = entry_;
        }

        private void buildPartial0(com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData result) {
          int from_bitField0_ = bitField0_;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData) {
            return mergeFrom((com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData other) {
          if (other == com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData.getDefaultInstance()) return this;
          if (!other.entry_.isEmpty()) {
            if (entry_.isEmpty()) {
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntryIsMutable();
              entry_.addAll(other.entry_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  java.lang.String s = input.readStringRequireUtf8();
                  ensureEntryIsMutable();
                  entry_.add(s);
                  break;
                } // case 10
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.LazyStringList entry_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureEntryIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            entry_ = new com.google.protobuf.LazyStringArrayList(entry_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <pre>
         * 可重复的 repeated
         * </pre>
         *
         * <code>repeated string entry = 1;</code>
         * @return A list containing the entry.
         */
        public com.google.protobuf.ProtocolStringList
            getEntryList() {
          return entry_.getUnmodifiableView();
        }
        /**
         * <pre>
         * 可重复的 repeated
         * </pre>
         *
         * <code>repeated string entry = 1;</code>
         * @return The count of entry.
         */
        public int getEntryCount() {
          return entry_.size();
        }
        /**
         * <pre>
         * 可重复的 repeated
         * </pre>
         *
         * <code>repeated string entry = 1;</code>
         * @param index The index of the element to return.
         * @return The entry at the given index.
         */
        public java.lang.String getEntry(int index) {
          return entry_.get(index);
        }
        /**
         * <pre>
         * 可重复的 repeated
         * </pre>
         *
         * <code>repeated string entry = 1;</code>
         * @param index The index of the value to return.
         * @return The bytes of the entry at the given index.
         */
        public com.google.protobuf.ByteString
            getEntryBytes(int index) {
          return entry_.getByteString(index);
        }
        /**
         * <pre>
         * 可重复的 repeated
         * </pre>
         *
         * <code>repeated string entry = 1;</code>
         * @param index The index to set the value at.
         * @param value The entry to set.
         * @return This builder for chaining.
         */
        public Builder setEntry(
            int index, java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          ensureEntryIsMutable();
          entry_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 可重复的 repeated
         * </pre>
         *
         * <code>repeated string entry = 1;</code>
         * @param value The entry to add.
         * @return This builder for chaining.
         */
        public Builder addEntry(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          ensureEntryIsMutable();
          entry_.add(value);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 可重复的 repeated
         * </pre>
         *
         * <code>repeated string entry = 1;</code>
         * @param values The entry to add.
         * @return This builder for chaining.
         */
        public Builder addAllEntry(
            java.lang.Iterable<java.lang.String> values) {
          ensureEntryIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, entry_);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 可重复的 repeated
         * </pre>
         *
         * <code>repeated string entry = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearEntry() {
          entry_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 可重复的 repeated
         * </pre>
         *
         * <code>repeated string entry = 1;</code>
         * @param value The bytes of the entry to add.
         * @return This builder for chaining.
         */
        public Builder addEntryBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          ensureEntryIsMutable();
          entry_.add(value);
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.striveonger.study.task.context.MessageBody.ColumnData)
      }

      // @@protoc_insertion_point(class_scope:com.striveonger.study.task.context.MessageBody.ColumnData)
      private static final com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData();
      }

      public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ColumnData>
          PARSER = new com.google.protobuf.AbstractParser<ColumnData>() {
        @java.lang.Override
        public ColumnData parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<ColumnData> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ColumnData> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int DATA_FIELD_NUMBER = 1;
    private static final class DataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData>newDefaultInstance(
                  com.striveonger.study.task.context.MessageBodyOuterClass.internal_static_com_striveonger_study_task_context_MessageBody_DataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData> data_;
    private com.google.protobuf.MapField<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData>
    internalGetData() {
      if (data_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DataDefaultEntryHolder.defaultEntry);
      }
      return data_;
    }
    public int getDataCount() {
      return internalGetData().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
     */
    @java.lang.Override
    public boolean containsData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData> getData() {
      return getDataMap();
    }
    /**
     * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData> getDataMap() {
      return internalGetData().getMap();
    }
    /**
     * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData getDataOrDefault(
        java.lang.String key,
        /* nullable */
com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData> map =
          internalGetData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
     */
    @java.lang.Override
    public com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData getDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData> map =
          internalGetData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetData(),
          DataDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData> entry
           : internalGetData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData>
        data__ = DataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, data__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody)) {
        return super.equals(obj);
      }
      com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody other = (com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody) obj;

      if (!internalGetData().equals(
          other.internalGetData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetData().getMap().isEmpty()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.striveonger.study.task.context.MessageBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.striveonger.study.task.context.MessageBody)
        com.striveonger.study.task.context.MessageBodyOuterClass.MessageBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.striveonger.study.task.context.MessageBodyOuterClass.internal_static_com_striveonger_study_task_context_MessageBody_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.striveonger.study.task.context.MessageBodyOuterClass.internal_static_com_striveonger_study_task_context_MessageBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.class, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.Builder.class);
      }

      // Construct using com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableData().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.striveonger.study.task.context.MessageBodyOuterClass.internal_static_com_striveonger_study_task_context_MessageBody_descriptor;
      }

      @java.lang.Override
      public com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody getDefaultInstanceForType() {
        return com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.getDefaultInstance();
      }

      @java.lang.Override
      public com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody build() {
        com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody buildPartial() {
        com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody result = new com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.data_ = internalGetData();
          result.data_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody) {
          return mergeFrom((com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody other) {
        if (other == com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.getDefaultInstance()) return this;
        internalGetMutableData().mergeFrom(
            other.internalGetData());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData>
                data__ = input.readMessage(
                    DataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableData().getMutableMap().put(
                    data__.getKey(), data__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData> data_;
      private com.google.protobuf.MapField<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData>
          internalGetData() {
        if (data_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              DataDefaultEntryHolder.defaultEntry);
        }
        return data_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData>
          internalGetMutableData() {
        if (data_ == null) {
          data_ = com.google.protobuf.MapField.newMapField(
              DataDefaultEntryHolder.defaultEntry);
        }
        if (!data_.isMutable()) {
          data_ = data_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return data_;
      }
      public int getDataCount() {
        return internalGetData().getMap().size();
      }
      /**
       * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
       */
      @java.lang.Override
      public boolean containsData(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetData().getMap().containsKey(key);
      }
      /**
       * Use {@link #getDataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData> getData() {
        return getDataMap();
      }
      /**
       * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData> getDataMap() {
        return internalGetData().getMap();
      }
      /**
       * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData getDataOrDefault(
          java.lang.String key,
          /* nullable */
com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData> map =
            internalGetData().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
       */
      @java.lang.Override
      public com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData getDataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData> map =
            internalGetData().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableData().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
       */
      public Builder removeData(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableData().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData>
          getMutableData() {
        bitField0_ |= 0x00000001;
        return internalGetMutableData().getMutableMap();
      }
      /**
       * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
       */
      public Builder putData(
          java.lang.String key,
          com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableData().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;string, .com.striveonger.study.task.context.MessageBody.ColumnData&gt; data = 1;</code>
       */
      public Builder putAllData(
          java.util.Map<java.lang.String, com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody.ColumnData> values) {
        internalGetMutableData().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.striveonger.study.task.context.MessageBody)
    }

    // @@protoc_insertion_point(class_scope:com.striveonger.study.task.context.MessageBody)
    private static final com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody();
    }

    public static com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageBody>
        PARSER = new com.google.protobuf.AbstractParser<MessageBody>() {
      @java.lang.Override
      public MessageBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageBody> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.striveonger.study.task.context.MessageBodyOuterClass.MessageBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_striveonger_study_task_context_MessageBody_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_striveonger_study_task_context_MessageBody_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_striveonger_study_task_context_MessageBody_ColumnData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_striveonger_study_task_context_MessageBody_ColumnData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_striveonger_study_task_context_MessageBody_DataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_striveonger_study_task_context_MessageBody_DataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MessageBody.proto\022\"com.striveonger.stu" +
      "dy.task.context\"\334\001\n\013MessageBody\022G\n\004data\030" +
      "\001 \003(\01329.com.striveonger.study.task.conte" +
      "xt.MessageBody.DataEntry\032\033\n\nColumnData\022\r" +
      "\n\005entry\030\001 \003(\t\032g\n\tDataEntry\022\013\n\003key\030\001 \001(\t\022" +
      "I\n\005value\030\002 \001(\0132:.com.striveonger.study.t" +
      "ask.context.MessageBody.ColumnData:\0028\001B$" +
      "\n\"com.striveonger.study.task.contextb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_striveonger_study_task_context_MessageBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_striveonger_study_task_context_MessageBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_striveonger_study_task_context_MessageBody_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_com_striveonger_study_task_context_MessageBody_ColumnData_descriptor =
      internal_static_com_striveonger_study_task_context_MessageBody_descriptor.getNestedTypes().get(0);
    internal_static_com_striveonger_study_task_context_MessageBody_ColumnData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_striveonger_study_task_context_MessageBody_ColumnData_descriptor,
        new java.lang.String[] { "Entry", });
    internal_static_com_striveonger_study_task_context_MessageBody_DataEntry_descriptor =
      internal_static_com_striveonger_study_task_context_MessageBody_descriptor.getNestedTypes().get(1);
    internal_static_com_striveonger_study_task_context_MessageBody_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_striveonger_study_task_context_MessageBody_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
